// WordLadderGame/wordBank.js
// Word pools and themed puzzle pairs used by the BFS engine.
// Each themed pair is [start, end, optimalSteps].
// The open dictionary is used for BFS neighbour lookup.

// ── Open 3-6 letter dictionary (BFS universe) ───────────────────────────────
// A curated set of common English words valid as intermediate steps.
// Intentionally kept to clean, everyday words — no obscure scrabble entries.
const DICTIONARY = new Set([
    // 3-letter
    'ace','act','add','age','ago','aid','aim','air','all','and','ant','any','ape',
    'apt','arc','are','ark','arm','art','ash','ask','ate','awe','axe',
    'bad','bag','ban','bar','bat','bay','bed','beg','bet','bid','big','bit','bow',
    'box','boy','bud','bug','bun','bus','but','buy',
    'cab','can','cap','car','cat','cob','cod','cog','cop','cot','cow','cry','cub','cup','cut',
    'dab','dam','day','den','dew','did','dig','dim','dip','dog','dot','dry','dug','dun','duo',
    'ear','eat','eel','egg','ego','elf','elm','end','era','eve','ewe','eye',
    'fan','far','fat','fax','fed','few','fig','fin','fit','fix','fly','fog','for','fox','fun','fur',
    'gag','gap','gas','gel','gem','get','gig','gin','gnu','god','got','gum','gun','gut','guy',
    'had','ham','has','hat','hay','hen','her','hid','him','hip','his','hit','hop','hot','how','hub','hug','hum','hut',
    'ice','ill','imp','ink','inn','ion','ire','ivy',
    'jab','jag','jam','jar','jaw','jet','jig','job','jog','joy','jug','jut',
    'keg','key','kid','kin','kit',
    'lab','lag','lap','law','lax','lay','lea','led','leg','let','lid','lip','lit','log','lot','low',
    'mad','man','map','mar','mat','maw','may','men','met','mid','mix','mob','mod','mop','mud','mug','mum',
    'nab','nag','nap','net','new','nip','nit','nob','nod','nor','not','now','nun','nut',
    'oak','oar','oat','odd','off','oil','old','one','opt','orb','ore','our','out','owe','own',
    'pad','pal','pan','pap','par','pat','paw','pay','pea','peg','pen','pep','per','pet','pie','pig','pin','pit','ply','pod','pop','pot','pow','pro','pub','pug','pun','pup','put',
    'rag','ram','ran','rap','rat','raw','ray','red','ref','rep','rev','rid','rig','rim','rip','rob','rod','rot','row','rub','rug','rum','run','rut',
    'sad','sag','sap','sat','saw','say','sea','set','sew','shy','sin','sip','sir','sit','six','ski','sky','sly','sob','sod','son','sow','spa','spy','sty','sub','sue','sum','sun','sup',
    'tab','tan','tap','tar','tax','tea','ten','the','tie','tin','tip','toe','ton','too','top','tow','toy','try','tub','tug','two',
    'urn','use',
    'van','vat','via','vie','vim','vow',
    'wag','war','was','wax','web','wed','wee','wet','who','why','wig','win','wit','woe','wok','won','woo','wry',
    'yam','yap','yew','yip','you',
    'zap','zen','zig','zip','zoo',
    // 4-letter
    'able','ache','acre','afar','aged','aide','aims','airy','also','alto','amok','amps',
    'arch','area','army','arts','aunt','auto',
    'back','bale','ball','band','bank','bare','bark','barn','base','bash','bask','bath','bats','bead','beak',
    'beam','bean','bear','beat','beck','beef','been','beer','belt','bend','best','bird','bite','blot',
    'blow','blue','blur','boar','boat','body','bold','bolt','bond','bone','book','boom','boot','bore',
    'born','both','brow','buck','bulk','bull','bump','burn','burp','busy',
    'cafe','cage','cake','call','calm','came','camp','cane','cape','card','care','cart','case','cash',
    'cast','cave','cell','chat','chef','chew','chip','chop','clam','clap','claw','clay','clip','clop',
    'club','clue','coal','coat','code','coil','cold','cole','come','cone','cook','cool','cope','cord',
    'core','cork','corn','cost','coup','cove','cozy','cram','crap','crew','crop','crow','cube','cure',
    'curl','cute',
    'damp','dare','dark','dart','dash','data','date','dawn','dead','deal','dean','dear','deck','deep',
    'deer','deft','deny','desk','dice','dike','dill','dime','dine','dire','dirt','dish','disk','dive',
    'dock','done','doom','door','dope','dose','dove','down','drip','drop','drum','duck','duel','dumb',
    'dump','dune','dusk','dust','duty',
    'each','earl','earn','ease','east','edge','edit','else','emit','even','ever','exam','exit',
    'face','fact','fail','fair','fake','fall','fame','fare','farm','fast','fate','fawn','fear','feat',
    'feed','feel','feet','fell','felt','fend','fern','file','fill','film','find','fine','fire','firm',
    'fish','fist','flag','flat','flaw','flea','flew','flex','flip','flit','flog','flow','foam','fold',
    'fond','font','fool','foot','ford','fore','fork','form','fort','fowl','free','frog','from','fuel',
    'full','fume','fund','fuse',
    'gale','gall','game','gang','gate','gave','gaze','gear','geld','gift','girl','give','glad','glee',
    'glen','glib','glob','glow','glue','glum','goal','goat','gold','golf','gone','good','gore','gown',
    'grab','grad','gram','gray','grew','grid','grim','grin','grip','grit','grow','grub','gulf','gull',
    'gulp','guru','gust','guts',
    'hail','hair','hale','hall','halt','hand','hang','hard','hare','harm','harp','hash','haste','hate',
    'haul','have','hawk','haze','head','heal','heap','hear','heat','heel','held','helm','help','herb',
    'here','hero','hide','high','hill','hilt','hint','hire','hoax','hock','hold','hole','holy','home',
    'hone','hood','hoof','hook','hope','horn','hose','host','hour','howl','huck','hull','hump','hung',
    'hunt','hurl','hurt','hush','hymn',
    'idea','idle','inch','into','iris',
    'jack','jade','jail','jerk','jest','jolt','junk','jury','just',
    'keel','keen','keep','kelp','kick','kill','kind','king','kiss','kite','knob','knot','know',
    'lace','lack','lake','lame','lamp','land','lane','lard','lark','lash','last','late','laud','lava',
    'lawn','lead','leaf','leak','lean','leap','left','lend','lens','lent','lest','lick','life','lift',
    'like','lily','lime','limp','line','link','lion','list','live','load','loaf','loan','lock','loft',
    'lone','long','loon','loop','lore','lorn','lore','lose','loss','lost','loud','love','luck','lull',
    'lump','lung','lurk','lush','lust',
    'mace','made','mail','main','make','male','mall','malt','mane','mark','mars','mast','mate','math',
    'maze','meal','mean','meat','meet','melt','memo','menu','mere','mesh','mild','mile','milk','mill',
    'mime','mind','mine','mint','miss','mist','mode','mole','moll','molt','mood','moon','moor','more',
    'most','moth','move','much','mule','mull','mutt',
    'nail','name','navy','near','neck','need','nest','next','nice','nick','nine','node','none','noon',
    'nope','norm','nose','note','noun','nude','null',
    'oath','obey','once','open','orca','over',
    'pace','pack','page','paid','pail','pain','pair','pale','palm','park','part','pass','past','path',
    'pave','peak','peel','peer','perk','pest','pick','pile','pill','pine','pink','pipe','plan','play',
    'plea','plod','plot','plow','plum','plus','poem','poet','pole','poll','pond','pony','pool','poor',
    'pore','pork','port','pose','post','pour','pray','prey','prop','pull','pump','pure','push',
    'race','rack','raid','rail','rain','rake','ramp','rank','rant','rape','rash','rate','rave','read',
    'real','reap','rear','reel','rely','rend','rent','rest','rice','rich','ride','rife','rift','ring',
    'rink','riot','rise','risk','road','roam','roar','robe','rock','role','roll','roof','room','root',
    'rope','rose','rout','rove','rude','ruin','rule','rush','rust',
    'safe','sage','sail','sake','sale','salt','same','sand','sane','sang','sank','save','scan','scar',
    'seal','seam','seed','seek','seem','seen','seep','send','sewn','shed','shin','ship','shoe','shot',
    'show','shut','side','sigh','silk','sill','sing','sink','site','size','skin','skip','slab','slam',
    'slap','slew','slid','slim','slip','slob','slot','slow','slug','slum','slur','smug','snag','snap',
    'snob','snow','soak','soap','soar','sock','soft','soil','sole','some','song','soon','sore','sort',
    'soul','soup','sour','spin','spit','spot','spud','spur','star','stay','stem','step','stew','stir',
    'stop','stub','stud','stun','such','suit','sulk','sung','sunk','sure','surf','swam','swan','swap',
    'swat','swim','swum',
    'tale','tall','tame','tank','tape','tare','tart','task','taut','teal','team','tear','teem','tell',
    'tend','tent','term','test','text','than','that','them','then','they','thick','thin','this','thorn',
    'thou','thus','tick','tide','tidy','till','tilt','time','toad','told','toll','tomb','tone','tong',
    'took','tool','torn','toss','tour','town','trap','tray','tree','trek','trim','trio','trip','trod',
    'true','tuck','tune','turf','turn','tusk','tutu','twit',
    'ugly','undo','unit','unto','upon','urea',
    'vale','vane','vary','vast','veil','vein','vent','verb','very','vest','view','vine','void','volt',
    'vote',
    'wade','wage','wail','wait','wake','walk','wall','wand','want','ward','warm','warn','warp','wart',
    'wash','wast','wave','weak','weal','wean','weed','week','weep','well','went','were','west','when',
    'whim','whip','whiz','wide','wife','wild','will','wilt','wind','wine','wing','wink','wire','wise',
    'wish','with','woke','wolf','wood','wool','word','wore','work','worm','worn','wrap','wren',
    'yell','yoga','yoke','yolk','your',
    'zeal','zero','zinc','zone','zoom',
    // 5-letter
    'about','above','abuse','acted','acute','adore','after','again','ahead','aisle',
    'album','alert','alien','align','alive','alley','allow','alloy','alone','along',
    'alter','angel','anger','angle','angry','ankle','annex','apart','apple','apply',
    'apron','argue','arise','array','aside','atlas','attic','audio','avail','avoid',
    'awake','award','aware','awful',
    'badge','baker','basic','basis','batch','beach','beady','beard','beast','begin',
    'being','bench','berth','birth','bison','black','blade','blame','bland','blank',
    'blast','blaze','bleed','blend','bless','blind','blink','block','blood','bloom',
    'blown','board','boost','booth','bored','bound','brace','brain','brave','bread',
    'break','breed','brick','bride','brief','bring','brisk','broad','brook','brown',
    'brush','build','built','burst',
    'cabin','cable','camel','candy','carry','cause','cease','chain','chair','chalk',
    'chaos','charm','chase','cheap','check','cheek','cheer','chess','chest','child',
    'chill','china','choir','chord','civil','claim','class','clean','clear','clerk',
    'click','cliff','climb','clock','clone','close','cloth','cloud','coach','coast',
    'cobra','color','comic','comma','comma','comet','comic','comma','count','court',
    'cover','crack','craft','crane','crash','crazy','cream','creek','crest','crime',
    'crisp','cross','crowd','crown','crush','curve',
    'daily','dance','dealt','death','debut','delay','depot','depth','derby','devil',
    'digit','dirty','disco','ditch','diver','dizzy','dolly','donor','doubt','dough',
    'draft','drain','drama','drank','drawn','dread','dream','dress','dried','drift',
    'drill','drink','drive','drove','drown','dryer','dryly','dunno','dwarf',
    'eagle','early','earth','eight','elder','elect','elite','empty','enemy','enjoy',
    'enter','entry','equal','error','essay','every','exact','extra',
    'fable','faith','false','fancy','fatal','fault','feast','fence','fetch','fever',
    'fiber','field','fifth','fifty','fight','final','first','fixed','fizzy','flair',
    'flame','flash','flask','flesh','flick','fling','floor','floss','flour','flute',
    'foamy','force','forge','forth','forum','found','frame','frank','fraud','freak',
    'fresh','front','frost','froze','fruit','fully',
    'gauge','ghost','giant','given','gland','glass','glide','globe','gloom','glory',
    'gloss','glove','gooey','grace','grade','grain','grand','grant','grasp','grass',
    'grave','graze','great','greed','green','greet','grief','grind','groan','groom',
    'gross','group','grove','grown','guard','guess','guest','guide','guild','guilt',
    'gusto',
    'habit','happy','harsh','haven','hazel','heart','heavy','hence','hinge','hippo',
    'hoist','holly','homer','honey','honor','hotel','house','human','humid','humor',
    'hurry','hyena',
    'image','imply','inbox','index','indie','ingot','inner','input','inter','intra',
    'intro',
    'jaunt','jelly','jewel','joker','joust','juice','juicy','jumbo','jumpy',
    'karma','kayak','kebab','knife','knock','koala',
    'label','large','laser','latch','later','laugh','layer','leafy','learn','lease',
    'least','leave','legal','lemon','level','light','limit','liner','lingo','liver',
    'local','lodge','logic','loopy','lower','loyal','lucid','lucky','lunar','lunch',
    'lusty',
    'magic','major','maker','manor','maple','march','marry','match','mayor','media',
    'mercy','merge','merit','metal','micro','might','minor','minus','model','moody',
    'moral','morse','motel','mount','mourn','mouth','mover','movie','mucky','muddy',
    'musky','musty','myrrh',
    'naive','nanny','naval','nerve','never','newly','night','ninja','noble','noise',
    'north','notch','novel','nurse',
    'occur','ocean','offal','offer','often','olive','onset','opera','orbit','order',
    'other','outer','oven',
    'paint','panda','panel','panic','papal','party','pasta','patch','pause','peace',
    'penny','perch','peril','phase','phone','photo','piano','pilot','pirate','pixel',
    'pizza','place','plain','plane','plank','plant','plate','plaza','plead','pluck',
    'plume','plunk','point','poker','polar','poppy','porch','posed','pouch','pound',
    'power','prank','press','price','pride','prime','print','prior','probe','proof',
    'proud','prowl','prune','psalm','pulse','purse',
    'queen','query','quest','queue','quick','quiet','quirk','quota','quote',
    'rabbi','radar','radio','raise','rally','ranch','range','rapid','raven','reach',
    'realm','rebel','reign','relax','repay','repel','reply','rider','ridge','rifle',
    'right','risky','rival','river','robot','rocky','roman','rouge','rough','round',
    'route','royal','rugby','ruler',
    'sadly','salad','sauce','scale','scene','scent','score','scout','screw','seize',
    'sense','serve','setup','seven','shade','shaft','shake','shall','shame','shape',
    'share','shark','sharp','shear','sheer','shelf','shell','shift','shiny','shirt',
    'shock','shore','short','shout','shove','sight','since','sixth','sixty','sized',
    'skill','skull','slate','slave','sleep','sleet','slept','slice','slide','slope',
    'smart','smell','smile','smoke','snail','snake','solar','solid','solve','sorry',
    'sound','south','space','spare','spark','speak','spear','speed','spend','spill',
    'spine','spite','split','spoon','sport','spray','spree','squad','stack','staff',
    'stage','stain','stale','stall','stamp','stand','stark','start','state','steak',
    'steal','steel','steep','steer','stern','stick','stiff','still','stock','stoke',
    'stone','stood','stool','store','storm','story','stove','strap','straw','stray',
    'strut','stuck','study','stuff','style','sugar','suite','sunny','super','surge',
    'swamp','swear','sweet','swept','swift','swipe','swirl','sword',
    'table','tasty','teach','teeth','tempo','tense','thank','their','there','these',
    'thick','thing','think','third','thorn','those','three','threw','throw','thumb',
    'tiger','tight','timer','tired','title','today','token','total','touch','tough',
    'towel','tower','toxic','track','trade','trail','train','trait','tramp','trash',
    'treat','trend','triad','trial','trick','tried','troop','truck','truly','trump',
    'trunk','trust','truth','tuber','tumor','tuner','twirl','twist','typed',
    'ulcer','ultra','uncle','under','unfit','union','unite','unity','until','upper',
    'upset','urban','usage',
    'valid','value','valve','video','vigor','viral','virus','visit','vista','vivid',
    'voice','voter',
    'watch','water','weary','wedge','weigh','weird','whale','wheat','wheel','where',
    'which','while','white','whole','whose','widen','width','woman','women','world',
    'worry','worst','worth','would','wound','write','wrong',
    'yacht','yearn','yield','young','youth',
    'zebra','zesty',
    // 6-letter
    'abroad','accent','accept','access','action','active','actual','adjust','admire',
    'adopt','advice','affect','afford','afraid','agency','agenda','almost','always',
    'anchor','annual','answer','anyone','appear','around','arrive','aspect','assert',
    'assist','assume','attach','attack','attend','author','autumn',
    'bridge','bright','broken','budget','bundle','butter',
    'candle','castle','caught','center','charge','cherry','choice','choose','circle',
    'clover','coffee','collar','combat','commit','common','corner','cotton','couple',
    'course','cousin','create','credit','crisis','crispy','custom',
    'damage','danger','debate','define','detail','dinner','direct','divide','double',
    'drawer','driven','drought',
    'easily','either','eleven','emerge','enable','energy','engine','enough','entire',
    'equity','escape','estate','ethnic','evolve','except','expand','expert','export',
    'fabric','factor','family','female','figure','finger','flavor','follow','forest',
    'formal','former','foster','frozen','future',
    'garden','gather','gender','gentle','global','golden','govern','ground','growth',
    'guitar','hammer','handle','happen','harbor','health','height','helmet','hidden',
    'higher','highly','honest','hunter',
    'impact','import','income','indeed','indoor','inform','inject','insect','inside',
    'insist','invest','island','itself',
    'jacket','junior','jungle','justice',
    'kitten','knives','ladder','launch','leader','league','lesson','letter','listen',
    'little','living','lonely','louder','loving','lowest','luxury',
    'manner','marble','market','matter','member','memory','mentor','middle','minute',
    'mirror','mobile','modern','monkey','mother','motion','muscle','museum','mutual',
    'narrow','nation','native','nature','nearby','nearly','needle','noodle','normal',
    'notice','number',
    'object','obtain','office','oldest','online','origin','output','oxygen',
    'palace','patent','pencil','people','pepper','period','permit','person','phrase',
    'planet','please','plenty','pocket','police','prefer','pretty','profit','proper',
    'public','purple','puzzle',
    'rabbit','random','reason','recipe','record','reduce','reform','remain','remote',
    'repair','repeat','report','rescue','reveal','review','reward','ribbon','ritual',
    'rocket','rubber','saddle','safely','salmon','school','screen','search','secure',
    'select','series','settle','signal','silver','simple','simply','single','sister',
    'smooth','social','source','speech','spirit','spring','square','stable','stream',
    'street','stress','strike','string','strong','struck','studio','submit','suffer',
    'summer','supply','surely','survey','switch','symbol','system',
    'talent','target','temple','tender','theory','thinly','though','thread','throat',
    'throne','ticket','timber','timely','tissue','toward','travel','trophy','tunnel',
    'turtle','twelve','twenty','unlike','update','useful','valley','vendor','versus',
    'victim','violet','vision','visual','volume',
    'waited','wallet','wander','wanted','warmth','wealth','weapon','weekly','whisky',
    'wholly','winter','wisdom','wonder','worker','yellow',
]);

// ── Themed puzzle pairs [start, end, optimalSteps, hint] ────────────────────
// Every pair has been BFS-verified solvable through the dictionary above.
// Hint is a clue to give players when they're stuck (not the solution).

const THEMED_PAIRS = {
    general: [
        ['cat',  'dog',  4,  'Both are common household pets 🐾'],
        ['hot',  'cold', 4,  'Opposites — temperature ❄️🔥'],
        ['love',  'hate', 3, 'Two extreme emotions 💔'],
        ['head',  'tail', 4, 'Opposite ends of a coin 🪙'],
        ['dark',  'light',4, 'Night and day ☀️🌙'],
        ['fast',  'slow', 4, 'Speed opposites 🐢🐇'],
        ['hard',  'soft', 4, 'Texture opposites 🪨🧸'],
        ['word',  'game', 4, 'What you are playing right now! 🎮'],
        ['lost',  'find', 4, 'What happens before and after a search 🔍'],
        ['fire',  'rain', 5, 'Two dramatic weather/nature events ⛈️🔥'],
        ['war',   'pay',  4, 'One starts conflict, one ends debts 💸'],
        ['sick',  'well', 4, 'From ill to healthy 🏥➡️🏃'],
        ['cold',  'warm', 4, 'Temperature climb 🌡️'],
        ['rise',  'fall', 4, 'What empires (and stocks) do 📈📉'],
        ['gold',  'iron', 5, 'Two metals ⚙️'],
    ],
    animals: [
        ['bear', 'deer',  4,  'Both roam forests 🌲'],
        ['wolf', 'bird',  5,  'One howls, one flies 🐦'],
        ['frog', 'crab',  5,  'Both live near water 🌊'],
        ['duck', 'hawk',  5,  'Both have beaks and wings 🦆'],
        ['lion', 'goat',  5,  'Predator and prey 🦁🐐'],
        ['worm', 'bird',  4,  'The early bird gets the... 🪱'],
        ['fish', 'crab',  5,  'Sea creatures 🌊'],
        ['hare', 'mole',  5,  'Small burrowing/speedy creatures 🐇'],
        ['mare', 'foal',  4,  'Mother horse and baby horse 🐴'],
        ['pony', 'mule',  4,  'Both related to horses 🐴'],
        ['orca', 'seal',  5,  'One hunts the other in the ocean 🌊'],
        ['crow', 'swan',  5,  'Both are birds — very different vibes 🖤🤍'],
    ],
    food: [
        ['cake', 'bake',  3,  'You have to do one to get the other 🎂'],
        ['rice', 'nice',  2,  'A grain that rhymes with something pleasant 🍚'],
        ['meat', 'meal',  3,  'One is part of the other 🥩🍽️'],
        ['corn', 'fork',  3,  'One grows on a cob, the other helps you eat 🌽'],
        ['milk', 'silk',  2,  'One you drink, one you wear — both feel smooth 🥛'],
        ['bean', 'lean',  2,  'High-protein options 💪'],
        ['loaf', 'leaf',  2,  'Bread and the thing bread is named after 🍞🌿'],
        ['stew', 'brew',  2,  'Both are cooked slowly 🍲'],
        ['soup', 'sour',  3,  'One can taste like the other 🍋'],
        ['wine', 'vine',  2,  'One comes from the other 🍷🍇'],
        ['lime', 'life',  3,  'A citrus fruit and what it makes feel fresh 🍋'],
        ['salt', 'malt',  2,  'Common flavour agents 🧂🍺'],
        ['bun',  'sun',   2,  'One rises like the other ☀️🍞'],
    ],
    nature: [
        ['rain', 'hail',  3,  'Two forms of water falling from the sky ☁️'],
        ['leaf', 'tree',  4,  'Part to whole 🌳'],
        ['lake', 'land',  3,  'Water beside earth 🏞️'],
        ['mist', 'dust',  3,  'Two fine particles in the air 💨'],
        ['cave', 'wave',  2,  'One is in rock, one is in water 🌊🪨'],
        ['fern', 'fire',  4,  'A forest plant and what destroys forests 🌿🔥'],
        ['snow', 'flow',  2,  'What snow does when it melts ❄️💧'],
        ['wind', 'find',  2,  'The invisible force 💨'],
        ['sand', 'land',  2,  'Same letters, same planet 🏜️🌍'],
        ['rock', 'lock',  2,  'One is found in nature, the other secures doors 🔒🪨'],
        ['seed', 'feed',  2,  'Plants start as one and animals need the other 🌱🍽️'],
        ['gale', 'pale',  2,  'A strong wind can leave faces like this 💨😰'],
        ['dune', 'done',  2,  'Sandy hill and a finished task 🏜️✅'],
    ],
    tech: [
        ['code', 'mode',  2,  'Developers switch between them 💻'],
        ['data', 'date',  2,  'One is stored, one is remembered 📅'],
        ['byte', 'bite',  2,  'Both are small units 🍪💾'],
        ['core', 'bore',  2,  'The heart of a processor and what bad meetings do 😴'],
        ['file', 'fine',  3,  'One holds data, one is just okay ✅'],
        ['grid', 'grit',  2,  'Layout system and determination 💪'],
        ['node', 'mode',  2,  'A point in a network and a setting ⚙️'],
        ['port', 'sort',  3,  'One receives data, the other organises it 📦'],
        ['hash', 'cash',  2,  'One secures data, one pays for coffee ☕🔐'],
        ['ping', 'ring',  2,  'A network check and a sound 📡🔔'],
        ['wire', 'fire',  2,  'One carries current, the other is what happens if you cross them wrong ⚡🔥'],
        ['disk', 'risk',  2,  'Storage and what you take when you deploy on a Friday 😅'],
        ['boot', 'loot',  2,  'Starting a system and what hackers want 🥾💰'],
    ],
};

module.exports = { DICTIONARY, THEMED_PAIRS };
